---
- name: Delete storage service (ceph)
  hosts: ceph
  tasks:
    - name: delete storage
      tags: ceph
      import_role:
        name: pbos.ceph
        tasks_from: delete

- name: Delete database service (mariadb)
  hosts: mariadb
  any_errors_fatal: true
  tasks:
    - name: delete mariadb
      tags: mariadb
      include_role:
        name: pbos.mariadb
        tasks_from: delete

#- name: Stop HA service (keepalived/haproxy)
#  hosts: controller
#  any_errors_fatal: true
#  tasks:
#    - name: stop keepalived
#      tags: keepalived
#      include_role:
#        name: pbos.keepalived
#        tasks_from: stop
#    - name: stop haproxy 
#      tags: haproxy
#      include_role:
#        name: pbos.haproxy
#        tasks_from: stop
#
#- name: Stop cache service (memcached)
#  hosts: controller
#  any_errors_fatal: true
#  tasks:
#    - name: stop memcached
#      tags: memcached
#      include_role:
#        name: pbos.memcached
#        tasks_from: stop
#
#- name: Stop database service (mariadb)
#  hosts: mariadb
#  any_errors_fatal: true
#  serial: 1
#  tasks:
#    - name: stop mariadb
#      tags: mariadb
#      include_role:
#        name: pbos.mariadb
#        tasks_from: stop
#
#- name: Stop messaging service (rabbitmq)
#  hosts: rabbitmq
#  any_errors_fatal: true
#  serial: 1
#  tasks:
#    - name: stop rabbitmq
#      tags: rabbitmq
#      include_role:
#        name: pbos.rabbitmq
#        tasks_from: stop
#
#- name: Stop openstack identity service (keystone)
#  hosts: keystone
#  any_errors_fatal: true
#  tasks:
#    - name: stop keystone
#      tags: keystone
#      include_role:
#        name: pbos.keystone
#        tasks_from: stop
#
#- name: Stop openstack image service (glance)
#  hosts: glance
#  any_errors_fatal: true
#  tasks:
#    - name: stop glance
#      tags: glance
#      include_role:
#        name: pbos.glance
#        tasks_from: stop
#
#
#- name: Stop openstack resource service (placement)
#  hosts: placement
#  any_errors_fatal: true
#  tasks:
#    - name: stop placement
#      tags: placement
#      include_role:
#        name: pbos.placement
#        tasks_from: stop
#
#- name: Stop openstack network service (neutron)
#  hosts: openstack
#  any_errors_fatal: true
#  tasks:
#    - name: stop neutron
#      tags: neutron
#      include_role:
#        name: pbos.neutron
#        tasks_from: stop
#
#- name: Stop openstack volume service (cinder)
#  hosts: cinder
#  any_errors_fatal: true
#  tasks:
#    - name: stop cinder
#      tags: cinder
#      include_role:
#        name: pbos.cinder
#        tasks_from: stop
#
#- name: Stop openstack compute service (nova)
#  hosts: openstack
#  any_errors_fatal: true
#  tasks:
#    - name: stop nova
#      tags: nova
#      include_role:
#        name: pbos.nova
#        tasks_from: stop
#
#- name: Stop openstack dashboard service (horizon)
#  hosts: controller
#  any_errors_fatal: true
#  tasks:
#    - name: stop horizon
#      tags: horizon
#      include_role:
#        name: pbos.horizon
#        tasks_from: stop
#
#- name: Stop openstack key management service (barbican)
#  hosts: barbican
#  any_errors_fatal: true
#  tasks:
#    - name: stop barbican
#      tags: barbican
#      include_role:
#        name: pbos.barbican
#        tasks_from: stop
...
