---
- name: Delete openstack dashboard service (horizon)
  hosts: controller
  any_errors_fatal: true
  tasks:
    - name: delete horizon
      tags:
        - horizon
        - openstack
      include_role:
        name: pbos.horizon
        tasks_from: delete

- name: Delete openstack key management service (barbican)
  hosts: barbican
  any_errors_fatal: true
  tasks:
    - name: delete barbican
      tags:
        - barbican
        - openstack
      include_role:
        name: pbos.barbican
        tasks_from: delete

- name: Delete openstack volume service (cinder)
  hosts: cinder
  any_errors_fatal: true
  tasks:
    - name: delete cinder
      tags:
        - cinder
        - openstack
      include_role:
        name: pbos.cinder
        tasks_from: delete

- name: Delete openstack compute service (nova)
  hosts: openstack
  any_errors_fatal: true
  tasks:
    - name: delete nova
      tags:
        - nova
        - openstack
      include_role:
        name: pbos.nova
        tasks_from: delete

- name: Delete openstack network service (neutron)
  hosts: openstack
  any_errors_fatal: true
  tasks:
    - name: delete neutron
      tags:
        - neutron
        - openstack
      include_role:
        name: pbos.neutron
        tasks_from: delete

- name: Delete openstack resource service (placement)
  hosts: placement
  any_errors_fatal: true
  tasks:
    - name: delete placement
      tags:
        - placement
        - openstack
      include_role:
        name: pbos.placement
        tasks_from: delete

- name: Delete openstack image service (glance)
  hosts: glance
  any_errors_fatal: true
  tasks:
    - name: delete glance
      tags:
        - glance
        - openstack
      include_role:
        name: pbos.glance
        tasks_from: delete

- name: Delete openstack identity service (keystone)
  hosts: keystone
  any_errors_fatal: true
  tasks:
    - name: delete keystone
      tags:
        - keystone
        - openstack
      include_role:
        name: pbos.keystone
        tasks_from: delete

- name: Delete messaging service (rabbitmq)
  hosts: rabbitmq
  any_errors_fatal: true
  tasks:
    - name: delete rabbitmq
      tags:
        - rabbitmq
        - pbos-infra
      include_role:
        name: pbos.rabbitmq
        tasks_from: delete

- name: Delete cache service (memcached)
  hosts: controller
  any_errors_fatal: true
  tasks:
    - name: delete memcached
      tags:
        - memcached
        - pbos-infra
      include_role:
        name: pbos.memcached
        tasks_from: delete

- name: Delete database service (mariadb)
  hosts: mariadb
  any_errors_fatal: true
  tasks:
    - name: delete mariadb
      tags:
        - mariadb
        - pbos-infra
      include_role:
        name: pbos.mariadb
        tasks_from: delete

- name: Delete HA service (keepalived/haproxy)
  hosts: controller
  any_errors_fatal: true
  tasks:
    - name: delete keepalived
      tags:
        - keepalived
        - pbos-infra
      include_role:
        name: pbos.keepalived
        tasks_from: delete
    - name: delete haproxy 
      tags:
        - haproxy
        - pbos-infra
      include_role:
        name: pbos.haproxy
        tasks_from: delete

- name: Delete storage service (ceph)
  hosts: ceph
  tasks:
    - name: delete storage
      tags:
        - ceph
        - pbos-storage
      import_role:
        name: pbos.ceph
        tasks_from: delete
...
