---
- hosts: all
  any_errors_fatal: true
  roles:
    - {role: pbos.ntp, tags: ntp}

- hosts: mariadb
  any_errors_fatal: true
  roles:
    - {role: pbos.mariadb, tags: mariadb}

- hosts: rabbitmq
  any_errors_fatal: true
  roles:
    - {role: pbos.rabbitmq, tags: rabbitmq}
...
