---
- hosts: all
  any_errors_fatal: true
  roles:
    - {role: pbos.ntp, tags: ntp}

- hosts: controller
  any_errors_fatal: true
  roles:
    - {role: pbos.keepalived, tags: keepalived}
    - {role: pbos.haproxy, tags: haproxy}
    - {role: pbos.memcached, tags: memcached}

- hosts: mariadb
  any_errors_fatal: true
  roles:
    - {role: pbos.mariadb, tags: mariadb}

- hosts: rabbitmq
  any_errors_fatal: true
  roles:
    - {role: pbos.rabbitmq, tags: rabbitmq}

- hosts: keystone
  any_errors_fatal: true
  roles:
    - {role: pbos.keystone, tags: keystone}

- hosts: glance
  any_errors_fatal: true
  roles:
    - {role: pbos.glance, tags: glance}

- hosts: placement
  any_errors_fatal: true
  roles:
    - {role: pbos.placement, tags: placement}

- hosts: openstack
  any_errors_fatal: true
  roles:
    - {role: pbos.neutron, tags: neutron}

- hosts: cinder
  any_errors_fatal: true
  roles:
    - {role: pbos.cinder, tags: cinder}

- hosts: openstack
  any_errors_fatal: true
  roles:
    - {role: pbos.nova, tags: nova}

- hosts: controller
  any_errors_fatal: true
  roles:
    - {role: pbos.horizon, tags: horizon}
...
