---
- name: Start time service (ntp)
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: start ntp
      tags:
        - ntp
        - pbos-infra
      include_role:
        name: pbos.ntp
        tasks_from: start

- name: Start HA service (keepalived/haproxy)
  hosts: controller
  any_errors_fatal: true
  tasks:
    - name: start keepalived
      tags:
        - keepalived
        - pbos-infra
      include_role:
        name: pbos.keepalived
        tasks_from: start
    - name: start haproxy 
      tags:
        - haproxy
        - pbos-infra
      include_role:
        name: pbos.haproxy
        tasks_from: start

- name: Start cache service (memcached)
  hosts: controller
  any_errors_fatal: true
  tasks:
    - name: start memcached
      tags: 
        - memcached
        - pbos-infra
      include_role:
        name: pbos.memcached
        tasks_from: start

- name: Start database service (mariadb)
  hosts: mariadb
  any_errors_fatal: true
  serial: 1
  tasks:
    - name: start mariadb
      tags:
        - mariadb
        - pbos-infra
      include_role:
        name: pbos.mariadb
        tasks_from: start

- name: Start messaging service (rabbitmq)
  hosts: rabbitmq
  any_errors_fatal: true
  serial: 1
  tasks:
    - name: start rabbitmq
      tags:
        - rabbitmq
        - pbos-infra
      include_role:
        name: pbos.rabbitmq
        tasks_from: start

- name: Start openstack identity service (keystone)
  hosts: keystone
  any_errors_fatal: true
  tasks:
    - name: start keystone
      tags:
        - keystone
        - openstack
      include_role:
        name: pbos.keystone
        tasks_from: start

- name: Start openstack image service (glance)
  hosts: glance
  any_errors_fatal: true
  tasks:
    - name: start glance
      tags:
        - glance
        - openstack
      include_role:
        name: pbos.glance
        tasks_from: start

- name: Start openstack resource service (placement)
  hosts: placement
  any_errors_fatal: true
  tasks:
    - name: start placement
      tags:
        - placement
        - openstack
      include_role:
        name: pbos.placement
        tasks_from: start

- name: Start openstack network service (neutron)
  hosts: openstack
  any_errors_fatal: true
  tasks:
    - name: start neutron
      tags:
        - neutron
        - openstack
      include_role:
        name: pbos.neutron
        tasks_from: start

- name: Start openstack volume service (cinder)
  hosts: cinder
  any_errors_fatal: true
  tasks:
    - name: start cinder
      tags:
        - cinder
        - openstack
      include_role:
        name: pbos.cinder
        tasks_from: start

- name: Start openstack compute service (nova)
  hosts: openstack
  any_errors_fatal: true
  tasks:
    - name: start nova
      tags:
        - nova
        - openstack
      include_role:
        name: pbos.nova
        tasks_from: start

- name: Start openstack dashboard service (horizon)
  hosts: controller
  any_errors_fatal: true
  tasks:
    - name: start horizon
      tags:
        - horizon
        - openstack
      include_role:
        name: pbos.horizon
        tasks_from: start

- name: Start openstack key management service (barbican)
  hosts: barbican
  any_errors_fatal: true
  tasks:
    - name: start barbican
      tags:
        - barbican
        - openstack
      include_role:
        name: pbos.barbican
        tasks_from: start
...
